---
- hosts: all
  tasks:
  - name: create nginx config directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
    with_items:
      - /etc/nginx
      - /etc/nginx/sites-enabled
      - /etc/nginx/ssl
      - /etc/nginx/snippets
  - name: copy nginx configs
    copy:
      src: "nginx/{{ item }}"
      dest: "/etc/nginx/{{ item }}"
      owner: root
      group: root
    with_items:
      - fastcgi.conf
      - fastcgi_params
      - koi-utf
      - koi-win
      - mime.types
      - nginx.conf
      - scgi_params
      - uwsgi_params
      - win-utf
      - sites-enabled/azure.com.conf
      - sites-enabled/cdn.galenguyer.com.conf
      - snippets/fastcgi-php.conf
      - ssl/dhparam.pem
      - ssl/params.conf
    notify: 
      - restart nginx
  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted
