---
- hosts: all
  tasks:
  - name: ensure personal gpg key is present in apt
    apt_key: 
      url: https://galenguyer.com/pubkey.txt
      state: present
  - name: ensure python3-apt is present for next steps
    apt:
      name: python3-apt
      state: present
  - name: ensure personal apt repo is present
    apt_repository:
      repo: deb https://packages.galenguyer.com/debian ./
      state: present
      update-cache: no
  - name: upate apt package list
    apt: 
      update_cache: yes
  - name: install edgeinx-mainline-quiche
    apt:
      name: edgeinx-mainline-quiche
      state: present
  - name: update packages
    apt:
      name: "*"
      state: latest
